services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: db_password_4321
      POSTGRES_USER: admin
      POSTGRES_DB: moviedb
    ports:
      - '9876:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
